<?

$TEMPLATE->js("//code.jquery.com/jquery-1.11.2.min.js");
$TEMPLATE->js("//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js");
$TEMPLATE->css("//maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css");
$TEMPLATE->css("https://cfp.openwest.org/assets/css/site.css");

?>
<div class="navbar navbar-opencfp navbar-fixed-top section--full" role="navigation">
	<a href="/" class="logo pull-left">
		<img src="https://cfp.openwest.org/uploads/openwest-white.svg" alt="OpenWest Conference CFP" style="max-width: 75%; position: absolute; top: 3px; left: 10px;">
	</a>
	<div class="navbar-header">
		<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
			<span class="sr-only">Toggle navigation</span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
			<span class="icon-bar"></span>
		</button>
	</div>
	<div class="collapse navbar-collapse">
		<ul class="nav navbar-nav navbar-right">
			<li><a href="https://cfp.openwest.org/">CFP</a></li>
			<li><a href="http://www.openwest.org/">OpenWest</a></li>
			<li><a href="http://www.utos.org/">UTOS</a></li>
		</ul>
	</div>
</div>
